#!/bin/bash
# Non-Polish users: English language support will be available in next version.
# Currently script supports only polish (pl_PL.UTF-8) locale.
#
# Instalator LibreOffice dla systemów z rodziny Ubuntu
# Licencja: GPLv3
# Autor: Admc
# Strona: http://www.ubuntu-pomoc.org/
# Copyright (C) 2012 Admc
#
# Niniejszy program jest wolnym oprogramowaniem: możesz go rozprowadzać
# dalej i/lub modyfikować na warunkach Powszechnej Licencji Publicznej GNU,
# wydanej przez Free Software Foundation, w wersji 3 lub (twój wybór) nowszej.
#
# Niniejszy program rozpowszechniany jest z nadzieją, iż będzie on użyteczny,
# ale BEZ JAKIEJKOLWIEK GWARANCJI, nawet bez dorozumianej gwarancji
# lub PRZYDATNOŚCI DO OKREŚLONEGO CELU. Zobacz Powszechną Licencję
# Publiczną GNU aby dowiedzieć się więcej.
#
# Do programu powinna być dołączona kopia Powszechnej Licencji Publicznej GNU.
# Jeśli nie, zobacz <http://www.gnu.org/licenses/>.
#---------------------------
# Wersja:
VESRION=0.2.2
#---------------------------
# FUNKCJE
#---------------------------
# Parametry wpisane z konsoli - funkcję wywoływać zawsze z $@
parameters(){
  while [ "$1" ] ; do 
    case "$1" in
    "--help"|"-h")
      echo -e "Instalator LibreOffice $VESRION
Opcje:
-v   --version			Wyświetl Informacje o wersji
-h   --help			Wyświetl tą informację
-l   --do-not-download		Nie pobieraj plików
-D   --download-only		Tylko pobierz Libre Office (nie instaluj)
     --disable-sha-check	Nie sprawdzaj sumy sha256 (niezalecane)
-d   --directory=KATALOG	Ręcznie ustaw katalog tymczasowy
     --force-32bit		Wymuś wersję 32-bitową (niezalecane)
     --force-64bit		Wymuś wersję 64-bitową (niezalecane)
-k   --force-kde		Wymuś włączenie integracji z KDE
     --integrate-with-kde	Tylko zintegruj z KDE (wymaga zainstalowanego LO)
-y   --no-questions		Udzielaj domyślnej odpowiedzi na pytania
-R   --remove-tmp-files		Usuń pliki tymczasowe
-C   --check-last-vesrion	Sprawdź najnowszą wersję Libre Office
-u   --uninstall		Usuń Libre Office
     --wipe			Usuń Libre Office i pliki konfiguracyjne"
      exit 0;
      ;;
    "--version"|"-v")
      echo -e "Instalator LibreOffice $VESRION\nTo jest wolne oprogramowanie: masz prawo je zmieniać i rozpowszechniać.\nAutor nie daje ŻADNYCH GWARANCJI w granicach dozwolonych prawem."
      exit 0;
      ;;
    "-d")
      if [ "$2" = "" ]; then
	echo -e "$0: Nie podano katalogu tymczasowego"
	exit 1;
      fi
      tmpdir="$2"
      shift;
      ;;
    "--directory="*)
      tmpdir=`echo -e "$1" | cut -c 13-`
      if [ "$tmpdir" = "" ]; then
	echo -e "$0: Nie podano katalogu tymczasowego"
	exit 1;
      fi
      ;;
    "--uninstall"|"-u")
      echo -e "Deinstalator Libre Office $VESRION\nTen skrypt pomoże ci odinstalować wszystkie wersje Libre Office z tego komputera"
      sudo -p "Podaj hasło administratora, jest ono wymagane do rozpoczęcia usuwania: " apt-get -y remove "libreoffice*.*" || exit 1;
      echo -e "Usuwanie Libre Office zakończone"
      exit 0;
      ;;
    "--wipe")
      echo -e "Deinstalator Libre Office $VESRION\nTen skrypt pomoże ci odinstalować wszystkie wersje oraz pliki konfiguracyjne\nLibre Office\nOSTRZEŻENIE: KONFIGURACJA LIBREOFFICE ZOSTANIE USUNIĘTA\nZaleca się użyć funkcji '--uninstall'"
      sudo -p "Podaj hasło administratora, jest ono wymagane do rozpoczęcia usuwania: " apt-get -y purge "libreoffice*.*" || exit 1;
      sudo -p "Podaj hasło administratora, jest ono wymagane do kontynuowania usuwania: " rm -rf /opt/libreoffice* || exit 1;
      rm -rf "$HOME/.libreoffice"
      rm -rf "$HOME/.config/libreoffice"
      echo -e "Usuwanie Libre Office i plików konfiguracyjnych zakończone"
      exit 0;
      ;;
    "--remove-tmp-files"|"-R")
      removefilesnow=true
      ;;
    "--check-last-vesrion"|"-C")
      check_last_lo_version
      exit 0;
      ;;
    "--do-not-download"|"-l")
      downloadfiles=false
      if [ "$do_not_install" = "true" ]; then
	echo -e "E: $0: Błędne opcje\nNie można jednocześnie pobierać i nie pobierać"
	exit 1;
      fi
      ;;
    "--disable-sha-check")
      checksha256sum=false
      ;;
    "--no-questions"|"-y")
      askquestions=false
      ;;
    "--download-only"|"-D")
      if [ "$downloadfiles" = "false" ]; then
	echo -e "E: $0: Błędne opcje\nNie można jednocześnie pobierać i nie pobierać"
	exit 1;
      fi
      do_not_install=true
      ;;
    "--force-32bit")
      archdir=x86
      archfile=x86
      arch_forced=true
      echo -e "OSTRZEŻENIE: Wymuszono architekturę procesora (x86)\nProgram może nie działać poprawnie!"
      ;;
    "--force-64bit")
      archdir=x86_64
      archfile=x86-64
      arch_forced=true
      echo -e "OSTRZEŻENIE: Wymuszono architekturę procesora (x86_64)\nProgram może nie działać poprawnie!"
      ;;
    "--force-kde"|"-k")
      force_kde=true
      ;;
    "--integrate-with-kde")
      enable_kde_integration
      exit 0;
      ;;
    *)
      echo -e "$0: Nieznana opcja '$1'\nWykonaj '$0 --help' dla uzyskania informacji"
      exit 1;
      ;;
    esac
    shift
  done
}
#---------------------------
# Testy przedinstalacyjne
tests(){
  detect_linux
  set_variables
  detect_ubuntu
  check_last_lo_version
  if [ "$do_not_install" != "true" ]; then
    detect_lo_from_repo
    detect_lo_from_df_site
  fi 
  if [ "$arch_forced" != "true" ]; then
    detect_arch
  fi
}
#---------------------------
# Instalacja właściwa
install_lo(){
  echo -en "Rozpocząć instalację? [T/n] "
  read_from_stdin a
  if [ "$a" = "n" -o "$a" = "N" ]; then
    exit 0;
  fi
# Tworzenie katalogu tymczasowego
  mkdir -p $tmpdir
# Przekształcenie ścieżki względnej w ścieżkę bezwzględną
  tmpdir=`cd $tmpdir; pwd`
# Pobieranie plików tymczasowych
if [ "$downloadfiles" != "false" ]; then
  download_lo_files
fi
# Sprawdzanie sumy sha-256
if [ "$checksha256sum" != "false" ]; then
  check_sha256sum
fi
# Rozpakowywanie plików
  unpack_files
# Instalacja
  install_deb_files
}
#---------------------------
# Ustawianie zmiennych
set_variables(){
# Katalogi
  firstdir=$pwd
  if [ "$tmpdir" = "" ]; then
    tmpdir=$HOME/.cache/libreoffice-installer
  fi
# Domyślnie nie usuwamy danych LO przed instalacją nowej wersji
  wipedata=false
}
#---------------------------
# Sprawdzanie czy jądro to Linux
detect_linux(){
if [ `uname -s` != "Linux" ]; then
  echo -e "Niewspierany system operacyjny (skrypt działa tylko na Linuxie)"
  exit 1;
fi
}
#---------------------------
# Sprawdzanie czy dystrybucja to Ubuntu
detect_ubuntu(){
  if test -x "`which lsb_release 2>/dev/null`"; then
    DISTRO=`lsb_release -s -i`
    if [ "$DISTRO" != "Ubuntu" ]; then
      echo -en "OSTRZEŻENIE: Wykryto, że używasz dystrybucji innej niż Ubuntu.\nSkrypt ten jest przeznaczony tylko dla Ubuntu i może nie działać poprawnie na uruchomionym systemie.\nCzy chcesz kontynować mimo to? [t/N] "
      read_from_stdin a
      if [ "$a" != "n" -a "$a" != "N" ]; then
	exit 0;
      fi
    fi
  else
    echo -en "OSTRZEŻENIE: Nie udało się wykryć dystrybucji.\nSkrypt ten jest przeznaczony tylko dla Ubuntu i może nie działać poprawnie na innym systemie.\nJeżeli używasz Ubuntu zainstaluj pakiet \"lsb-release\" i uruchom ponownie ten skrypt.\nCzy chcesz kontynować mimo to? [t/N] "
    read_from_stdin a
    if [ "$a" != "t" -a "$a" != "T" ]; then
      exit 0;
    fi
  fi
}
#---------------------------
# Detekcja architektury procesora
detect_arch(){
  case `arch` in 
    i[3456789]86|x86|i86pc)
      echo -e "Twój system jest 32-bitowy"
      archdir=x86
      archfile=x86
      ;;
    x86_64|amd64|AMD64)
      echo -e "Twój system jest 64-bitowy"
      archdir=x86_64
      archfile=x86-64
      ;;
    *)
      echo -e "Nieobsługiwana lub błędnie wykryta architektura procesora\nMożesz ustawić architekurę procesora ręcznie NA WŁASNĄ ODPOWIEDZIALNOŚĆ\n\t1) 32 bity\n\t2) 64 bity\nDowolny inny klawisz zamknąć instalator"
      read_from_stdin wyborarch
      case "$wyborarch" in
	"1") archdir=x86 && archfile=x86;;
	"2") archdir=x86_64 && archfile=x86-64;;  
	*) exit 0;;
      esac
      ;;
  esac
}
#---------------------------
# Sprawdzanie wersji LibreOffice
check_last_lo_version(){
  echo -e "Sprawdzanie najnowszej wersji LibreOffice..."
  lolastversion=`wget http://www.libreoffice.org/download/ -q -T 10 -O /dev/stdout | grep -o "version [0-9].[0-9].." | awk '{print $2}'`
  lolastversion_second_number=`echo -e $lolastversion | cut -c 3`
  if [ "$lolastversion" = "" ]; then
    echo -e "Wystąpił błąd przy sprawdzaniu najnowszej wersji LibreOffice, sprawdź połączenie z internetem."
    exit 1;
  fi
  echo "Ostatnia wersja LibreOffice to: "$lolastversion
}
#---------------------------
# Sprawdzanie czy LO jest już zainstalowane z repo
detect_lo_from_repo(){
  if test -x "`which libreoffice 2>/dev/null`"; then
    echo -en "Wykryto że LibreOffice jest już zainstalowany z repozytorium.\nZaleca się usunięcie go przed instalacją wersji ze strony DF aby uniknąć\nkonflików.\nCzy chcesz to zrobić? [T/n] "
    read_from_stdin a
    if [ "$a" != "n" -a "$a" != "N" ]; then
      wipedata=true
    fi
  fi
}
#---------------------------
# Sprawdzanie czy LO ze strony DF jest zainstalowane
detect_lo_from_df_site(){
  lofromdffolder=`ls /opt | grep libreoffice`
  if [ "$lofromdffolder" != "" ]; then
    loinstalledver=`dpkg -l | grep -m 1 libreoffice[0-9].[0-9] | grep -o [0-9].[0-9].[0-9] | head -n 1`
    loinstalledver_second_number=`echo -e $loinstalledver | cut -c 3`
    if [ "$loinstalledver" = "$lolastversion" ]; then
      echo -e "Masz już zainstalowaną najnowszą wersję LibreOffice. Co chcesz zrobić?\n\t1) Nadpisz instalację\n\t2) Nadpisz instalację z uprzednim usunięciem poprzedniej\nDowolny inny klawisz aby zamknąć instalator"
      read_from_stdin wyborinst
      case "$wyborinst" in
	"1") wipedata=false ;;
	"2") wipedata=true ;;
	*) exit 0;;
      esac
    fi
    if [ "$loinstalledver" != "$lolastversion" ]; then
      echo -e "Masz już zainstalowaną starszą wersję LibreOffice. Instalacja zostanie nadpisana."
    fi
    if [ "$loinstalledver_second_number" != "$lolastversion_second_number" ]; then
      wipedata=true
    fi
  fi
}
#---------------------------
# Pobieranie plików tymczasowych
download_lo_files(){
  wget http://download.documentfoundation.org/libreoffice/stable/$lolastversion/deb/$archdir/LibO_"$lolastversion"_Linux_"$archfile"_install-deb_en-US.tar.gz -O "$tmpdir/install.tar.gz"
  wget http://download.documentfoundation.org/libreoffice/stable/$lolastversion/deb/$archdir/LibO_"$lolastversion"_Linux_"$archfile"_langpack-deb_pl.tar.gz -O "$tmpdir/langpack.tar.gz"
  wget http://download.documentfoundation.org/libreoffice/stable/$lolastversion/deb/$archdir/LibO_"$lolastversion"_Linux_"$archfile"_helppack-deb_pl.tar.gz -O "$tmpdir/helppack.tar.gz"
}
#---------------------------
# Sprawdzanie sumy sha-256
check_sha256sum(){
  sha256instorig=`wget http://download.documentfoundation.org/libreoffice/stable/$lolastversion/deb/$archdir/LibO_"$lolastversion"_Linux_"$archfile"_install-deb_en-US.tar.gz.sha256 -q -O /dev/stdout | grep Lib0* | awk '{print $1}'`
  sha256instdown=`sha256sum "$tmpdir/install.tar.gz" | awk '{print $1}'`
  sha256langorig=`wget http://download.documentfoundation.org/libreoffice/stable/$lolastversion/deb/$archdir/LibO_"$lolastversion"_Linux_"$archfile"_langpack-deb_pl.tar.gz.sha256 -q -O /dev/stdout | grep Lib0* | awk '{print $1}'`
  sha256langdown=`sha256sum "$tmpdir/langpack.tar.gz" | awk '{print $1}'`
  sha256helporig=`wget http://download.documentfoundation.org/libreoffice/stable/$lolastversion/deb/$archdir/LibO_"$lolastversion"_Linux_"$archfile"_helppack-deb_pl.tar.gz.sha256 -q -O /dev/stdout | grep Lib0* | awk '{print $1}'`
  sha256helpdown=`sha256sum "$tmpdir/helppack.tar.gz" | awk '{print $1}'`
  if [ "$sha256instorig" != "$sha256instdown" -o "$sha256langorig" != "$sha256langdown" -o "$sha256helporig" != "$sha256helpdown" ]; then
    clear
    echo -e "Pliki tymczasowe są USZKODZONE\nUruchom skrypt ponownie aby ponowić próbę instalacji."
    exit 1;
  fi
}
#---------------------------
# Rozpakowywanie plików
unpack_files(){
  tar -C "$tmpdir/" -xvzf "$tmpdir/install.tar.gz"
  tar -C "$tmpdir/" -xvzf "$tmpdir/helppack.tar.gz"
  tar -C "$tmpdir/" -xvzf "$tmpdir/langpack.tar.gz"
}
#---------------------------
# Wykrycie KDE
detect_kde(){
  if [ "$force_kde" = "true" ]; then
    enable_kde_integration
  else
    if [ x"$KDE_FULL_SESSION" = x"true" ]; then
      echo -en "Wykryto że twoje środowisko graficzne to KDE,\nczy chcesz włączyć integrację LibreOffice z KDE? [T/n] "
      read_from_stdin a
      if [ "$a" != "n" -a "$a" != "N" ]; then
	enable_kde_integration
      fi
    fi
  fi
}
#---------------------------
# Włącenie integracji z KDE
enable_kde_integration(){
  installdir=`ls /opt |grep libreoffice`
  libstdc_path=`find "/opt/$installdir" -name *libstdc++* | grep libstdc++ | grep -v orig`
  sudo -p "Podaj hasło administratora, jest ono wymagane do włączenia integracji z KDE: " mv $libstdc_path "$libstdc_path"_orig  || exit 1;
}
#---------------------------
# Instalacja
install_deb_files(){
  clear
  (
  cd $tmpdir
  if $wipedata ; then
    sudo -p "Podaj hasło administratora, jest ono wymagane do ukończenia instalacji: " apt-get -y purge "libreoffice*.*" || exit 1;
    old_lo_dir=`ls /opt |grep -m1 libreoffice`
    if [ "$old_lo_dir" != "" ]; then
      dir_to_delete="/opt/$old_lo_dir"
      sudo -p "Podaj hasło administratora, jest ono wymagane do ukończenia instalacji: " rm -rf "$dir_to_delete" || exit 1;
    fi
  fi
  sudo -p "Podaj hasło administratora, jest ono wymagane do ukończenia instalacji: " su -c "find . -name *.deb | xargs dpkg -i" || exit 1;
  )||exit 1;
  clear
# Integracja z KDE
  detect_kde
  echo -en "Instalacja została zakończona, czy chcesz usunąć pliki tymczasowe? [T/n] "
  read_from_stdin a
  if [ "$a" = "n" -o "$a" = "N" ]; then
    exit 0;
  fi
  rm_tmp_files
}
#---------------------------
# Usuwanie plików tymczasowych
rm_tmp_files(){
  if [ "$tmpdir" = "" ]; then
    tmpdir=$HOME/.cache/libreoffice-installer
  fi
  rm -rf $tmpdir
}
#---------------------------
# Wczytaj tekst z klawiatury
read_from_stdin(){
if [ "$askquestions" != "false" ]; then
  read $1
fi
}
#---------------------------
# Tylko pobieranie
only_download_lo_files(){
  tests
#Tworzenie katalogu tymczasowego
  mkdir -p $tmpdir
#Przekształcenie ścieżki względnej w ścieżkę bezwzględną
  tmpdir=`cd $tmpdir; pwd`
#Pobieranie plików tymczasowych
  download_lo_files
  exit 0;
}
#---------------------------
# KONIEC FUNKCJI
#---------------------------
# POCZĄTEK SKRYPTU
#---------------------------
parameters $@
if [ "$do_not_install" ]; then
  only_download_lo_files
fi
if [ "$removefilesnow" ]; then
  rm_tmp_files
  exit 0;
fi
clear
echo -e "Instalator LibreOffice $VESRION\nTen skrypt umożliwia łatwą instalację LibreOffice ze strony Document Fundation"
# Testy przedinstalacyjne
tests
# Instalacja właściwa
install_lo
exit 0